workflows:
  android-app:
    name: Build Android APK
    environment:
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web app
        script: npm run build
      - name: Ensure Android project exists
        script: |
          if [ ! -d android ]; then
            npx cap add android
          fi
      - name: Sync Capacitor Android
        script: npx cap sync android
      - name: Build APK (release)
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
