name: Android APK (Debug + Full Logs)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print repo & android tree
        run: |
          pwd
          ls -la
          echo "---- android ----"
          ls -la android || true
          echo "---- app ----"
          ls -la android/app || true
          echo "---- wrapper ----"
          ls -la android/gradle/wrapper || true
          echo "---- web assets ----"
          ls -la android/app/src/main/assets/public || true

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew || true

      - name: Show Gradle projects & tasks (debug info)
        working-directory: android
        run: |
          ./gradlew projects --no-daemon || true
          ./gradlew tasks --no-daemon || true

      - name: Build APK (Debug) with verbose logs
        working-directory: android
        env:
          ORG_GRADLE_PROJECT_org.gradle.warning.mode: all
        run: |
          set -e
          ./gradlew assembleDebug --no-daemon --stacktrace --info || {
            echo "==== PROBLEMS REPORT (if present) ===="
            if [ -d build/reports/problems ]; then
              for f in build/reports/problems/*; do
                echo "::group::$(basename "$f")"
                sed -n '1,250p' "$f" || true
                echo "::endgroup::"
              done
            fi
            echo "==== LAST 200 lines of Gradle log (if any) ===="
            find . -name "*.log" -type f -maxdepth 4 -print -exec tail -n 200 {} \; || true
            exit 1
          }

      - name: Upload any APK found
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            android/**/outputs/apk/**/*.apk
            android/**/outputs/**/*.apk
          if-no-files-found: warn
