name: Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew || true

      # Build global (ça a déjà marché chez toi)
      - name: Build assembleDebug (global)
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon --stacktrace --info

      - name: List produced artifacts
        run: |
          find android -type f \( -name "*.apk" -o -name "*.aab" \) -print || true
          ls -la android/app/build/outputs || true
          ls -la android/app/build/outputs/apk || true
          ls -la android/app/build/outputs/apk/debug || true
          ls -la android/app/build/outputs/bundle || true

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: |
            android/app/build/outputs/apk/**/*.apk
            android/**/outputs/**/*.apk
            android/**/outputs/**/*.aab
          if-no-files-found: warn
