name: Android APK (catch artifacts)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew || true

      # Build le module 'app' en Debug (le plus sûr)
      - name: Build :app:assembleDebug
        working-directory: android
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace --info

      # En plus, tente un release (si dispo) sans faire échouer le job
      - name: Optional :app:assembleRelease
        working-directory: android
        run: ./gradlew :app:assembleRelease --no-daemon --stacktrace --info || true

      # Liste tout ce qui ressemble à un artefact (debug/release, apk/aab)
      - name: List produced artifacts
        run: |
          echo "== Listing outputs =="
          find android -type f \( -name "*.apk" -o -name "*.aab" \) -print || true
          echo "== Tree of standard output dirs =="
          ls -la android/app/build/outputs || true
          ls -la android/app/build/outputs/apk || true
          ls -la android/app/build/outputs/apk/debug || true
          ls -la android/app/build/outputs/apk/release || true
          ls -la android/app/build/outputs/bundle || true

      # Upload APK + AAB où qu'ils soient
      - name: Upload artifacts (APK/AAB)
        uses: actions/upload-artifact@v4
        with:
          name: app-builds
          path: |
            android/**/outputs/**/*.apk
            android/**/outputs/**/*.aab
          if-no-files-found: warn
