name: Android APK (auto-detect module)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew || true

      # Montre la topologie Gradle pour trouver le bon module
      - name: Show settings & projects
        working-directory: android
        run: |
          echo "=== settings.gradle(.kts) ==="
          (cat settings.gradle || true)
          (cat settings.gradle.kts || true)
          echo "=== gradlew projects ==="
          ./gradlew projects --no-daemon || true

      # Auto-détection du module : on cherche un projet qui ressemble à app/android
      - name: Build assembleDebug on detected module
        working-directory: android
        run: |
          set -e
          MOD=$(
            ./gradlew projects --no-daemon \
            | sed -n "s/^Project '\\(.*\\)'$/\\1/p" \
            | grep -E "(:app$|:android$|:capacitor.*|:mobile$)" \
            | head -n1
          )
          if [ -z "$MOD" ]; then
            echo "⚠️  Aucun module détecté par heuristique; tentative sur :app"
            MOD=":app"
          fi
          echo "➡️  Module ciblé = $MOD"
          ./gradlew ${MOD}:assembleDebug --no-daemon --stacktrace --info

      # Optionnel : on tente aussi un release, sans casser le job si ça échoue
      - name: Optional assembleRelease
        working-directory: android
        run: |
          set +e
          for M in :app :android ; do
            ./gradlew ${M}:assembleRelease --no-daemon --stacktrace --info && break
          done
          true

      # Listing clair des artefacts produits
      - name: List produced artifacts
        run: |
          echo "== APK/AAB trouvés =="
          find android -type f \( -name "*.apk" -o -name "*.aab" \) -print || true
          echo "== Dossiers outputs =="
          ls -la android/app/build/outputs || true
          ls -la android/app/build/outputs/apk || true
          ls -la android/app/build/outputs/apk/debug || true
          ls -la android/app/build/outputs/apk/release || true
          ls -la android/app/build/outputs/bundle || true

      # Upload APK/AAB où qu'ils soient
      - name: Upload artifacts (APK/AAB)
        uses: actions/upload-artifact@v4
        with:
          name: app-builds
          path: |
            android/**/outputs/**/*.apk
            android/**/outputs/**/*.aab
          if-no-files-found: warn
