name: Android APK (Debug + Error reveal)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew || true

      - name: Gradle debug build (capture FULL log)
        working-directory: android
        run: |
          ./gradlew --version
          set +e
          ./gradlew assembleDebug --no-daemon --stacktrace --warning-mode all --console=plain | tee gradle-debug.log
          EXIT=$?
          echo "==== SEARCH 'What went wrong' in gradle-debug.log ===="
          grep -n "What went wrong" gradle-debug.log || true
          echo "==== LAST 400 lines of gradle-debug.log ===="
          tail -n 400 gradle-debug.log || true

          echo "==== Problems report (if present) – plain text ===="
          if [ -d build/reports/problems ]; then
            for f in build/reports/problems/*; do
              echo "::group::$(basename "$f")"
              sed -e 's/<[^>]*>//g' -e 's/&nbsp;/ /g' -e 's/&gt;/>/g' -e 's/&lt;/</g' -e 's/&amp;/&/g' "$f" | sed -n '1,400p' || true
              echo "::endgroup::"
            done
          fi
          if [ -d app/build/reports/problems ]; then
            for f in app/build/reports/problems/*; do
              echo "::group::app/$(basename "$f")"
              sed -e 's/<[^>]*>//g' -e 's/&nbsp;/ /g' -e 's/&gt;/>/g' -e 's/&lt;/</g' -e 's/&amp;/&/g' "$f" | sed -n '1,400p' || true
              echo "::endgroup::"
            done
          fi
          exit $EXIT

      - name: Upload ANY APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: android/**/outputs/**/*.apk
          if-no-files-found: warn
