name: Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew

      # 🟢 Étape diagnostic
      - name: Print Gradle settings & projects
        working-directory: android
        run: |
          echo "===== settings.gradle ====="
          (cat settings.gradle 2>/dev/null || true)
          echo "===== settings.gradle.kts ====="
          (cat settings.gradle.kts 2>/dev/null || true)
          echo "===== ./gradlew -q projects ====="
          ./gradlew -q projects || true

      - name: Build assembleDebug (global) + full log
        working-directory: android
        run: |
          set +e
          ./gradlew assembleDebug --no-daemon --stacktrace --warning-mode all --console=plain | tee build.log
          status=${PIPESTATUS[0]}
          echo "==== What went wrong (grep) ===="
          grep -n "What went wrong" -n build.log -A 40 || true
          exit $status

      - name: Try :app:assembleDebug if global failed
        if: failure()
        working-directory: android
        run: |
          ./gradlew :app:assembleDebug --no-daemon --stacktrace --warning-mode all --console=plain | tee build-app.log

      - name: Upload Gradle logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            android/build.log
            android/build-app.log
          if-no-files-found: ignore

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: |
            android/app/build/outputs/apk/**/*.apk
            android/**/outputs/**/*.apk
            android/**/outputs/**/*.aab
          if-no-files-found: warn
