name: Android APK (Debug + MAX logs)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show trees
        run: |
          pwd && ls -la
          echo "---- android ----" && ls -la android || true
          echo "---- wrapper ----" && ls -la android/gradle/wrapper || true
          echo "---- app ----" && ls -la android/app || true
          echo "---- web assets ----" && ls -la android/app/src/main/assets/public || true

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew || true

      - name: Gradle debug build (capture FULL log)
        working-directory: android
        run: |
          set -euo pipefail
          ./gradlew --version
          ./gradlew assembleDebug --no-daemon --stacktrace --info --console=plain | tee gradle-debug.log

      # Si ça a échoué, on imprime les rapports détaillés AVANT d’échouer le job
      - name: Dump Gradle problem reports
        if: failure()
        working-directory: android
        run: |
          echo "==== SEARCH 'What went wrong' in gradle-debug.log ===="
          grep -n "What went wrong" -n gradle-debug.log || true
          echo "==== LAST 300 lines of gradle-debug.log ===="
          tail -n 300 gradle-debug.log || true

          echo "==== Problems reports (if any) ===="
          if [ -d build/reports/problems ]; then
            for f in build/reports/problems/*; do
              echo "::group::$(basename "$f")"
              sed -n '1,400p' "$f" || true
              echo "::endgroup::"
            done
          fi
          if [ -d app/build/reports/problems ]; then
            for f in app/build/reports/problems/*; do
              echo "::group::app/$(basename "$f")"
              sed -n '1,400p' "$f" || true
              echo "::endgroup::"
            done
          fi

      - name: Upload ANY APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: android/**/outputs/**/*.apk
          if-no-files-found: warn
