      # 1) Lister la config & les modules
      - name: Print Gradle settings & projects
        working-directory: android
        run: |
          echo "===== settings.gradle ====="
          (cat settings.gradle 2>/dev/null || true)
          echo "===== settings.gradle.kts ====="
          (cat settings.gradle.kts 2>/dev/null || true)
          echo "===== ./gradlew -q projects ====="
          ./gradlew -q projects || true

      # 2) Build global + log complet
      - name: Build assembleDebug (global) + full log
        working-directory: android
        run: |
          set +e
          ./gradlew assembleDebug --no-daemon --stacktrace --warning-mode all --console=plain | tee build.log
          status=${PIPESTATUS[0]}
          echo "==== What went wrong (grep) ===="
          grep -n "What went wrong" -n build.log -A 40 || true
          exit $status

      # 3) Si échec, tenter le module :app explicitement
      - name: Try :app:assembleDebug if global failed
        if: failure()
        working-directory: android
        run: |
          ./gradlew :app:assembleDebug --no-daemon --stacktrace --warning-mode all --console=plain | tee build-app.log

      # 4) Uploader les logs pour qu’on voie l’erreur réelle
      - name: Upload Gradle logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            android/build.log
            android/build-app.log
          if-no-files-found: ignore
